  #     Variables that will need to be changed:
  #
  #     PGID                            -  Group id for folder/file permissions
  #     PATH_TO_CONFIG                  -  Path to folder of config files
  #     REMOTE_IP                       -  Remote IP address of CIFS mount
  #     PATH_TO_DB                      -  Path to your service's database
  #     PATH_TO_LIBRARY                 -  Path to folder of library files 
  #     USERNAME                        -  Remote mount username
  #     PASSWORD                        -  Remote mount password


---
version: "3.8"

services:
  caddy:
  #reverse-proxy
    image: caddy:2.7.6-alpine
    container_name: caddy
    restart: always
    networks:
      - caddy_reverse_proxy
    cap_add:
      - NET_ADMIN
    ports:
      - 80:80
      - 443:443
    volumes:
      - PATH_TO_DATA:/data
      - PATH_TO_CONFIG:/config
      - PATH_TO/Caddyfile:/etc/caddy/Caddyfile:ro

networks:
  caddy_reverse_proxy:
    driver: "bridge"
    name: caddy
