  #     Variables that may need to be changed:
  #     PUID                            -  User id for folder/file permissions
  #     PGID                            -  Group id for folder/file permissions
  #     PATH_TO_CONFIG                  -  Path to folder of config files
  #     REMOTE_IP                       -  Remote IP address of CIFS mount
  #     PATH_TO_DB                      -  Path to your service's database
  #     PATH_TO_LIBRARY                 -  Path to folder of library files 
  #     USERNAME                        -  Remote mount username
  #     PASSWORD                        -  Remote mount password


---
version: "3.8"
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    user: 1000:1000
    ports:
      - 4533:4533
    environment:
    # https://www.navidrome.org/docs/usage/external-integrations/#spotify
      - ND_LASTFM_APIKEY=xxx
      - ND_LASTFM_SECRET=xxx
      - ND_SPOTIFY_ID=xxx
      - ND_SPOTIFY_SECRET=xxx
      - ND_DEFAULTTHEME=dark
      - ND_ENABLEGRAVATAR=true
      - ND_ENABLESHARING=true
      - ND_ENABLEFAVOURITES=true
      - ND_AUTOIMPORTPLAYLISTS=false
    volumes:
      - PATH_TO_DB:/data
      - music_db:/music:ro
volumes:
  music_db:
    driver_opts:
      type: cifs
      o: "username=USERNAME,password=PASSWORD"
      device: //PATH_TO_LIBRARY/Music
