  # Variables that will need to be changed:
  #     PUID                            -  User id for folder/file permissions
  #     PGID                            -  Group id for folder/file permissions
  #     PATH_TO_CONFIG                  -  Path where config files are stored
  #     REMOTE_IP                       -  Remote IP address of CIFS mount
  #     PATH_TO_LIBRARY                 -  Path in remote machine to be mounted as your library 
  #     USERNAME                        -  Remote mount username
  #     PASSWORD                        -  Remote mount password

---
version: "3.8"

services:
  uptime-kuma:
  #Easy-to-use self-hosted monitoring tool
  #https://github.com/louislam/uptime-kuma
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - kuma_db:/app/data
    ports:
      - 9999:3001
    restart: always

  pairdrop:
  #Self-Hosted AirDrop Alternative
  #https://github.com/schlagmichdoch/PairDrop
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - WS_FALLBACK=false 
      - RATE_LIMIT=false
      - TZ=America/Phoenix 
    ports:
      - 127.0.0.1:3000:3000

volumes:
#SMB Shares to be Mounted
  kuma_db:
    driver_opts:
      type: cifs
      o: "username=USERNAME,password=PASSWORD"
      device: "//PATH_TO_CONFIG/uptime-kuma"
