  # Variables that will need to be changed:
  #     PUID                            -  User id for folder/file permissions
  #     PGID                            -  Group id for folder/file permissions
  #     PATH_TO_CONFIG                  -  Path where config files are stored
  #     REMOTE_IP                       -  Remote IP address of CIFS mount
  #     PATH_TO_LIBRARY                 -  Path in remote machine to be mounted as your library 
  #     USERNAME                        -  Remote mount username
  #     PASSWORD                        -  Remote mount password


---
version: "3.8"

services:
  plex:
  #Movie/TV Media Server
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Phoenix
      - VERSION=docker
      - PLEX_CLAIM= #https://www.plex.tv/claim/
    volumes:
      - PATH_TO_LIBRARY:/config
      - PATH_TO_CONFIG:/tv
      - PATH_TO_CONFIG:/movies
    restart: unless-stopped

  komga:
  #Comic Book Server
    image: gotson/komga:latest
    container_name: komga
    volumes:
      - comic_lib:/data
      - PATH_TO_CONFIG:/config
    ports:
      - 7500:8080
    restart: unless-stopped
    environment:
      - TZ=America/Phoenix
      - JAVA_TOOL_OPTIONS=-Xmx2g

  fireshare:
  #Self-Hosted Clip Sharing
    image: shaneisrael/fireshare:latest
    container_name: fireshare
    restart: unless-stopped
    ports:
      - 9500:80
    volumes:
      - PATH_TO_CONFIG:/data
      - PATH_TO_CONFIG:/processed
      - shared_clips:/videos
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
      - SECRET_KEY=*********
      - MINUTES_BETWEEN_VIDEO_SCANS=1
      - PUID=1000
      - PGID=1000

volumes:
#SMB Shares to be Mounted
#I recommend using a READONLY account here
  comic_lib:
    driver_opts:
      type: cifs
      o: "username=USERNAME,password=PASSWORD"
      device: "//REMOTE_IP/Comics"
  plex_tv:
    driver_opts:
      type: cifs
      o: "username=USERNAME,password=PASSWORD"
      device: "//REMOTE_IP/Television"
  plex_movies:
    driver_opts:
      type: cifs
      o: "username=USERNAME,password=PASSWORD"
      device: "//REMOTE_IP/Movies"
  shared_clips:
    driver_opts:
      type: cifs
      o: "username=USERNAME,password=PASSWORD"
      device: "//REMOTE_IP/Videos/SharedClips"
